### PR TITLE
Fix tail-based sampling discarding low throughput and low sample rate traces

### LINKED ISSUE #11372: Tail-based sampling discards all traces when sampling rate and throughput are low
**APM Server version** (`apm-server version`): 8.9.0

**Description of the problem including expected versus actual behavior**:

Let's say we have a service that produces 4 transactions per minute, and we have configured tail-based sampling with a rate of 0.1. Roughly speaking, we calculate the desired number of traces as `sample_rate * ingest_rate`, rounding half away from zero. In this case, that would be 4*0.1=0.4 -- so the desired total number of traces is calculated as zero.

Even at low throughput we should be using random sampling. In the above scenario there should be a 10% chance of capturing any one trace. That may still lead to infrequently captured traces -- users can then address this by adding more specific sampling policies with higher sampling rates for their low-throughput services.

**Steps to reproduce**:

 1. Send 4 transactions every minute to apm-server
 2. Configure TBS with a single policy with a sample rate of 0.1
 3. Observe that no trace events are even indexed

Sample event generator:

```go
package main

import (
        "time"

        "go.elastic.co/apm/v2"
)

func main() {
        tracer := apm.DefaultTracer()
        defer tracer.Flush(nil)

        ticker := time.NewTicker(time.Minute)
        for range ticker.C {
                for i := 0; i < 4; i++ {
                        tx := tracer.StartTransaction("name", "type")
                        tx.Duration = time.Duration(i+1) * time.Second
                        tx.End()
                }
        }
}
```

### PR DESCRIPTION
**Pull request by carsonip**
## Motivation/summary

In tail-based sampling, use math.ceil instead of math.Round when computing desired total such that on low throughput and low sample rate traces e.g. throughput=1, sample rate = 0.4, desired total = math.Ceil(1 * 0.4) = 1 as opposed to 0 when using math.Round. This will fix cases where these traces were missing before the fix.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

Enable TBS, set sample rate to 0.4, send 1 trace. Check if the trace shows up.

## Related issues

Closes #11372

### CODE REVIEW

File: x-pack/apm-server/sampling/groups.go [hunk 1]
```diff
@@ -224,7 +224,7 @@ func (g *traceGroup) finalizeSampledTraces(traceIDs []string, ingestRateDecayFac
 
 	// Resize the reservoir, so that it can hold the desired fraction of
 	// the observed ingest rate.
-	newReservoirSize := int(math.Round(g.samplingFraction * g.ingestRate))
+	newReservoirSize := int(math.Ceil(g.samplingFraction * g.ingestRate))
```
Comment (carsonip) [inline x-pack/apm-server/sampling/groups.go:227]: [For reviewer] I don't think this is needed for the fix to work, and that we have a min size. But might be good to be consistent and use math.Ceil in all samplingFraction multiplication.

**Review by axw — APPROVED** [review]
LGTM, thank you

**Comment by lahsivjar** [comment]
Tested successfully by enabling TBS with a low sample rate and sending a single trace, the trace was indexed successfully.
