### PR TITLE
Change server information endpoint `/` to only accept GET and HEAD requests

### LINKED ISSUE #15965: Return an error on POST requests to `/`
From https://discuss.elastic.co/t/not-seeing-logs-from-otel-collector-in-apm/375275

As apm-server accepts HTTP GET and POST (and possibly more) to path `/`, it is easy for users to misconfigure otlphttp exporter to send to `http://apm-server/` instead of `http://apm-server/v1/traces`. Even worse, because the endpoint always return 200, any otlphttp misconfiguration would fail silently, causing a poor user experience.

```
carson@carson-elastic:~$ curl localhost:8200/
{
  "build_date": "0001-01-01T00:00:00Z",
  "build_sha": "unknown",
  "publish_ready": false,
  "version": "8.19.0"
}
carson@carson-elastic:~$ curl -XPOST localhost:8200/
{
  "build_date": "0001-01-01T00:00:00Z",
  "build_sha": "unknown",
  "publish_ready": false,
  "version": "8.19.0"
}
```

Proposed fix: return 405 (or any 4xx) for POST requests to `/`, and possibly include a helpful error message, asking if the user wants to send to `POST /intake/v2/events` or `POST /v1/*` otlphttp endpoints instead.

### PR DESCRIPTION
**Pull request by carsonip**
## Motivation/summary

Breaking change to change server information endpoint / to only accept GET and HEAD requests, and return 405 Method Not Allowed otherwise. This will surface any agent misconfiguration, e.g. configuring otlphttp to send to / instead of /v1/traces.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Documentation has been updated: https://github.com/elastic/docs-content/pull/647

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

```shell
curl -XGET -v http://apm-server/
curl -XHEAD -v http://apm-server/
curl -XPOST -v http://apm-server/
```

Confirm that GET and HEAD requests return 200, POST requests return 405.

## Related issues

Fixes #15965

### CODE REVIEW

File: internal/beater/api/root/handler.go [hunk 1]
```diff
@@ -38,10 +40,21 @@ type HandlerConfig struct {
...
-
 	return func(c *request.Context) {
+		// Only allow GET, HEAD requests
+		switch c.Request.Method {
+		case http.MethodGet, http.MethodHead:
+		default:
+			c.Result.SetWithError(
+				request.IDResponseErrorsMethodNotAllowed,
+				// include a verbose error message to alert users about a common misconfiguration
+				errors.New("this is the health check endpoint; did you mean to send data to another endpoint instead?"),
```
Comment (carsonip) [inline internal/beater/api/root/handler.go:52]: [to reviewer] lmk if this is too verbose, I can revert the commit.

```
$ curl -XPOST -v localhost:8200/
* Host localhost:8200 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8200...
* connect to ::1 port 8200 from ::1 port 49848 failed: Connection refused
*   Trying 127.0.0.1:8200...
* Connected to localhost (127.0.0.1) port 8200
> POST / HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Mon, 03 Mar 2025 16:35:38 GMT
< Content-Length: 129
< 
{
  "error": "method not supported: this is the health check endpoint; did you mean to send data to another endpoint instead?"
}
* Connection #0 to host localhost left intact
```

File: docs/spec/openapi/paths/server_info.yaml [hunk 2]
```diff
@@ -15,11 +15,3 @@ get:
   responses:
     '200':
       $ref: '../components/responses/200_server_info.yaml'
-post:
```
Comment (carsonip) [inline docs/spec/openapi/paths/server_info.yaml:18]: [to reviewer] other than openapi spec, we'll also need to remove it from obs docs in a separate PR: https://www.elastic.co/guide/en/observability/current/apm-api-info.html

File: internal/beater/api/root/handler.go (hunk 1 above)
Comment (rubvs) [reply internal/beater/api/root/handler.go:52]: I think it's fine.

**Review by 1pkg — DISMISSED** [review]

File: docs/spec/openapi/paths/server_info.yaml (hunk 2 above)
Comment (endorama) [reply docs/spec/openapi/paths/server_info.yaml:18]: Why would you remove it? I would add a disclaimer that the `/` endpoint is to be used fr healthcheck or test only, but I think the use case of POST with credentials (to verify credentials) is a nice one to give our user guidance on. I would definitely clarify its purpose though.

**Review by endorama — DISMISSED** [review]
Overall good to me, thanks Carson!

File: docs/spec/openapi/paths/server_info.yaml (hunk 2 above)
Comment (carsonip) [reply docs/spec/openapi/paths/server_info.yaml:18]: the intention of this very PR is to remove the "functionality" to POST to `/`. As such, we are removing the corresponding part in the docs. If we don't remove it in the docs, we'll be left with docs that reference an endpoint that doesn't work.

Comment (carsonip) [reply docs/spec/openapi/paths/server_info.yaml:18]: > I think the use case of POST with credentials (to verify credentials) is a nice one to give our user guidance on

I agree that we should update the docs to state that we can optionally provide credentials on the GET request to get additional info about the server. But I'm not sure if OpenAPI spec supports that.

**Review by simitt — APPROVED** [review]

**Review by simitt — APPROVED** [review]

**Comment by rubvs** [comment]
## Test Plan for v9.1.0


- Commit BEFORE change: `git checkout b17bf3460`
- Spin up local APM Server
```shell
> curl -X GET -v http://localhost:8200/
```
```json
{
  "log.level": "info",
  "@timestamp": "2025-06-18T12:05:54.958-0400",
  "log.logger": "request",
  "log.origin": {
    "function": "github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1",
    "file.name": "middleware/log_middleware.go",
    "file.line": 62
  },
  "message": "request ok",
  "service.name": "apm-server",
  "url.original": "/",
  "http.request.method": "GET",
  "user_agent.original": "curl/8.7.1",
  "source.address": "127.0.0.1",
  "http.request.id": "a9fa6cfd-61cf-441e-8494-f0a8ce5467a2",
  "event.duration": 399334,
  "http.request.body.bytes": 0,
  "http.response.status_code": 200,
  "ecs.version": "1.6.0"
}
```

```shell
> curl -X HEAD -v http://localhost:8200/
```
```json
{
  "log.level": "info",
  "@timestamp": "2025-06-18T12:04:03.125-0400",
  "log.logger": "request",
  "log.origin": {
    "function": "github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1",
    "file.name": "middleware/log_middleware.go",
    "file.line": 62
  },
  "message": "request ok",
  "service.name": "apm-server",
  "url.original": "/",
  "http.request.method": "HEAD",
  "user_agent.original": "curl/8.7.1",
  "source.address": "127.0.0.1",
  "http.request.id": "ba41b345-8428-445b-aaee-fcc902db53d5",
  "event.duration": 111166,
  "http.request.body.bytes": 0,
  "http.response.status_code": 200,
  "ecs.version": "1.6.0"
}
```

```shell
> curl -X POST -v http://localhost:8200/
```
```json
{
  "log.level": "info",
  "@timestamp": "2025-06-18T12:04:55.830-0400",
  "log.logger": "request",
  "log.origin": {
    "function": "github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1",
    "file.name": "middleware/log_middleware.go",
    "file.line": 62
  },
  "message": "request ok",
  "service.name": "apm-server",
  "url.original": "/",
  "http.request.method": "POST",
  "user_agent.original": "curl/8.7.1",
  "source.address": "127.0.0.1",
  "http.request.id": "b48adab3-58aa-4204-9950-dadbb7ba3c12",
  "event.duration": 84334,
  "http.request.body.bytes": 0,
  "http.response.status_code": 200,
  "ecs.version": "1.6.0"
}
```

- Commit AFTER change: `git checkout 2aaa73a56`

```shell
> curl -X HEAD -v http://localhost:8200/
```
```json
{
  "log.level": "error",
  "@timestamp": "2025-06-18T12:07:01.079-0400",
  "log.logger": "request",
  "log.origin": {
    "function": "github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1",
    "file.name": "middleware/log_middleware.go",
    "file.line": 59
  },
  "message": "method not supported",
  "service.name": "apm-server",
  "url.original": "/",
  "http.request.method": "POST",
  "user_agent.original": "curl/8.7.1",
  "source.address": "127.0.0.1",
  "http.request.id": "f023bc87-5e22-4c5b-bb08-80155d8177ee",
  "event.duration": 570875,
  "http.request.body.bytes": 0,
  "http.response.status_code": 405,
  "error.message": "method not supported: this is the server information endpoint; did you mean to send data to another endpoint instead?",
  "ecs.version": "1.6.0"
}
```
