### PR TITLE
sampling: use a data stream for sampled trace docs

### LINKED ISSUE #4584: Tail-sampling: transactions are being duplicated
**APM Server version** (`apm-server version`):

7.11.0 BC1

**Description of the problem including expected versus actual behavior**:

With tail-based sampling enabled, transactions are being indexed twice in Elasticsearch. Transactions should be indexed once at most.

**Steps to reproduce**:

 1. Enable tail-based sampling, with a catch-all policy with sample_rate 0.999
 2. Send 100 transactions (single service)
 3. Wait for the sampling interval to elapse.
 4. Query the cardinality of `transaction.id` in the transactions index; it should match the number of docs.

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Update tail-based sampling to index into and search a data stream. The data stream will be associated with an ILM policy that takes care of rollover and deletion.

When running in Fleet-managed mode, apm-server will expect the data stream and ILM policy to exist for the data stream called `traces-sampled-<namespace>`. Servers participating in tail-based sampling are required to be configured with the same namespace.

When running in standalone mode, apm-server will attempt to create an index template and ILM policy for a data stream called `apm-sampled-traces`. This is added for minimal support while we transition things to Fleet, and is intended to be removed in a future release. The data stream is not intended to adhere to the standard indexing strategy.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes

`cd systemtest && go test -v -run TailSampling`

For manual testing:
 - see https://github.com/elastic/apm-server/issues/4584 for how to test the fix for original issue
 - run apm-server with tail sampling enabled:
   - ensure an index template and ILM policy both called "apm-sampled-traces" are created
   - ensure a data stream called "apm-sampled-traces"

It's not currently possible to configure tail sampling with Fleet, so no testing steps are described for those parts. Just check that installing the package leads to the "sampled_traces" data stream index template, ILM policy, and ingest pipeline being installed.

## Related issues

Closes #4584

### CODE REVIEW

**Comment by axw** [comment]
jenkins run the tests please

File: x-pack/apm-server/sampling/pubsub/datastream.go [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+	}
+	defer resp.Body.Close()
+	if resp.IsError() {
+		body, _ := ioutil.ReadAll(resp.Body)
+		return fmt.Errorf("failed to create index template (%d): %s", resp.StatusCode, body)
+	}
+	return nil
+}
+
+const ilmPolicy = `{
```
Comment (simitt) [inline x-pack/apm-server/sampling/pubsub/datastream.go:61]: can you crosslink to the apmpackage policy to ensure they are kept in sync (even when unlikely to change)

**Review by simitt — APPROVED** [review]

File: x-pack/apm-server/main.go [hunk 2]
```diff
@@ -108,6 +109,31 @@ func newTailSamplingProcessor(args beater.ServerParams) (*sampling.Processor, er
...
+	} else {
+		sampledTracesDataStream = sampling.DataStreamConfig{
+			Type:      "apm",
+			Dataset:   "sampled",
+			Namespace: "traces",
+		}
+		if err := pubsub.SetupDataStream(context.Background(), es,
+			"apm-sampled-traces", // Index template
+			"apm-sampled-traces", // ILM policy
+			"apm-sampled-traces", // Index pattern
```
[the remark this answers is not in the document]
Comment (axw) [reply x-pack/apm-server/main.go:130]: I didn't bother because the feature is subject to breaking changes, and the mapping is very minimal anyway. If we need to version we can always tack on a version later, and this one effectively becomes v0.

File: x-pack/apm-server/sampling/pubsub/datastream.go (hunk 1 above)
Comment (axw) [reply x-pack/apm-server/sampling/pubsub/datastream.go:61]: Will do :+1:

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
On second thoughts, merging - the apm-it failure is clearly not related to this. It's been flaky recently.
