### PR TITLE
Seperate Processors and Payloads

### LINKED ISSUE #96: Discrepancy between agent.name and language.name in context
Steps to reproduce: Expand any document in the Discover table to review the context info.

screenshot 2017-08-24 10 57 34

### PR DESCRIPTION
**Pull request by roncohen**
Fixes #96.

Tests were updated so they reuse processors, like we do in the actual server code.

### CODE REVIEW

**Comment by ruflin** [comment]
This does not only seem to fix the bug we had in our code but I think it also makes the code more readable. 👍 

@roncohen You need to rebase. Seems you used an old version of master :-)

File: beater/server.go [hunk 1]
```diff
@@ -101,13 +101,13 @@ func createHandler(p processor.Processor, config Config, publish successCallback
...
 		limitedReader := io.LimitReader(reader, config.MaxUnzippedSize)
-		err = p.Validate(limitedReader)
+		payload, err := p.Validate(limitedReader)
 		if err != nil {
 			sendError(w, r, 400, fmt.Sprintf("Data Validation error: %s", err), true)
 			return
 		}
 
-		list := p.Transform()
+		list := payload.Transform()
```
Comment (simitt) [inline beater/server.go]: We made the `payload.transform()` method private. I think `p.Transform(payload)` should be the way to go.

File: processor/transaction/processor.go [hunk 2]
```diff
@@ -20,22 +19,17 @@ const (
...
 
-func (p *processor) Transform() []beat.Event {
-	return p.payload.transform()
-}
-
-func (p *processor) Validate(reader io.Reader) error {
-	return pr.Validate(reader, p.schema, p.payload)
+func (p *processor) Validate(reader io.Reader) (pr.Payload, error) {
+	var payload Payload
+	return &payload, pr.Validate(reader, p.schema, &payload)
```
Comment (simitt) [inline processor/transaction/processor.go]: what do you think about returning the validated `payload` from the `pr.Validate` method?

File: beater/server.go (hunk 1 above)
Comment (simitt) [inline beater/server.go]: I would not expose the `payload` here, but rather handle it as an interna of `processor`. The publicly known and agreed interface is `Processor` which offers a `Validate(..)` and a `Transform(..)` method.

File: processor/transaction/processor.go (hunk 2 above)
Comment (roncohen) [inline processor/transaction/processor.go]: `pr.Validate` is used both by errors and processors. It's generic: https://github.com/elastic/apm-server/blob/master/processor/validator.go#L26

But the Payloads are different. One is from the error package and one is from the transaction package. Suggestions are welcome.

File: beater/server.go (hunk 1 above)
Comment (roncohen) [inline beater/server.go]: I considered that, but it means the interface will have a method: `Transform(Payload)` which takes a `Payload` interface. If we remove the `Transform` method from the `Payload` interface, there's nothing left. So it take an empty interface, which could be anything. 

Also, the `Transform` method would look like this. Notice the need to type assert `pr.Payload` to an actual struct:

```
func (p *processor) Transform(payload pr.Payload) []beat.Event {
	var events []beat.Event
	pa := payload.(Payload)
	for _, tx := range pa.Events {

		events = append(events, pr.CreateDoc(tx.Mappings(pa)))

		for _, tr := range tx.Traces {
			events = append(events, pr.CreateDoc(tr.Mappings(pa, tx)))
		}
	}

	return events
}
```

File: processor/transaction/processor.go (hunk 2 above)
Comment (roncohen) [inline processor/transaction/processor.go]: or did you mean to both take it as the third argument by reference (like in the suggested above) _and_ return it?

File: beater/server.go (hunk 1 above)
Comment (simitt) [inline beater/server.go]: I think we currently mix `Validation` and `Transformation` together, which is more appearant now than it was before. 
How about clearly separating those two steps, e.g.
```
var buf bytes.Buffer
dataReader := io.TeeReader(reader, &buf)
err := processor.Validate(dataReader)
//do some error check
processor.Transform(buf.Bytes)
```

I have not done a test implementation, but I think it should also be easier to keep the internal logic private then.

File: processor/transaction/processor.go (hunk 2 above)
Comment (crackerplace) [inline processor/transaction/processor.go]: @simitt If I were to add few points here,I like what you said and returning payload sounds better.

As we are registering the processors only once using NewProcessor,they are singleton.So,ideally our processor methods which act on input request should be stateless and and not mutate data(payload) but instead work like functions.

Comment (simitt) [inline processor/transaction/processor.go]: @roncohen as this all plays together, please see my [comment above](https://github.com/elastic/apm-server/pull/98/files#r135033960)

**Comment by roncohen** [comment]
I took another round on this now:
* Payload is private and the interface is gone again.
* I took JSON unmarshalling out of `Validate` and put it in `Transform` now as suggested by @simitt.
* Both `Validate` and `Transform` simply take `[]byte` now. `Validate` used to take an `io.Reader` but I also changed that to `[]byte` so it consistent now. The same `[]byte` can be used for both calls after each other. The alternative was for both of them to take an io.Reader and then use TeeReader to split the stream, but in the end that would mean all the data will be in memory anyway and we'd have the added complexity of the TeeReader.

If you're reviewing this, you should probably look at the holistic view and not the individual commits, as the latest one reverts some of the changes done in the first.

File: beater/server.go [hunk 3]
```diff
@@ -101,13 +101,20 @@ func createHandler(p processor.Processor, config Config, publish successCallback
 
 		// Limit size of request to prevent for example zip bombs
 		limitedReader := io.LimitReader(reader, config.MaxUnzippedSize)
-		err = p.Validate(limitedReader)
+
+		buf, err := ioutil.ReadAll(limitedReader)
```
Comment (ruflin) [inline beater/server.go]: I remember there was a reason I passed the reader instead of the buffer to Validate, but I can't see why anymore.

**Comment by crackerplace** [comment]
@roncohen Just incase this helps,don't we want to handle error [here](https://github.com/roncohen/apm-server/blob/fix-96/processor/transaction/processor.go#L42) and [here](https://github.com/roncohen/apm-server/blob/fix-96/processor/transaction/processor.go#L42) so as to avoid calling publish.

File: processor/transaction/processor.go [hunk 4]
```diff
@@ -39,7 +39,8 @@ func (p *processor) Transform(buf []byte) []beat.Event {
 	err := json.Unmarshal(buf, &pa)
 	if err != nil {
 		logp.Err("Error while unmarshaling data: %v", err)
-		return nil
+		// Effectively drop the data
+		return []beat.Event{}
```
Comment (ruflin) [inline processor/transaction/processor.go]: @roncohen I would probably even prefer if Transform could also return an error, so logging and treating of the error would happen in the server. Like this we only do it in one place. Also it would make testing `Transform` simpler I would think.

**Comment by roncohen** [comment]
Following @crackerplace's comment I've changed it to return an empty list of `Event`s instead of `nil` if JSON unmarshalling in `Transform` fails - which shouldn't happen if our JSON Spec is always good.

**Comment by ruflin** [comment]
@roncohen Left an additional comment on the last commit. I would prefer that we even return an error as I think it makes the code cleaner.

**Comment by ruflin** [comment]
@roncohen Run `make fmt`, it seems pep8 does not like your python formatting.

**Comment by roncohen** [comment]
@ruflin OK, fixed.

**Comment by roncohen** [comment]
Rebased and update commit msg.

**Comment by ruflin** [comment]
@roncohen Great step forward in cleaning up the code (and fixing the bug ;-) )
@crackerplace Thanks for your reviews here.
