### PR TITLE
Read sourcemap content and fill context lines

### LINKED ISSUE #457: Add actual source to stacktrace frame when applying sourcemapping
Add the `pre_context`, `post_context` and `context_line` information when sourcmap mapping is applied to a stacktrace frame of an incoming request.

### PR DESCRIPTION
**Pull request by jalvz**
fixes #457

### CODE REVIEW

File: sourcemap/mapper.go [hunk 1]
```diff
@@ -4,10 +4,14 @@ import (
 	"fmt"
 	"time"
 
+	"strings"
+
 	"github.com/elastic/beats/libbeat/common"
 	"github.com/elastic/beats/libbeat/logp"
 )
 
+const sourcemapContentSnippetSize = 5
```
Comment (simitt) [inline sourcemap/mapper.go]: This could have a huge impact on the used storage so I suggest to make this configurable.

File: sourcemap/mapper.go [hunk 2]
```diff
@@ -71,3 +82,16 @@ func (m *SmapMapper) NewSourcemapAdded(id Id) {
 	}
 	m.Accessor.Remove(id)
 }
+
+func subSlice(from, to int, content []string) []string {
+	if from > len(content) {
+		return content
```
Comment (simitt) [inline sourcemap/mapper.go]: If I read correct, then in this case we would store the whole `content`. I suggest to return an empty array and to log an error.

Comment (jalvz) [reply sourcemap/mapper.go]: this is for when source content is not available, will rewrite to `if len(content) == 0` to make it clear; sorry for that.
not sure about logging an error, sourcemap content is optional (as per spec); i think some tools include it by default and others don't, users can choose.
you still think should be logged?

File: sourcemap/mapper.go (hunk 1 above)
Comment (jalvz) [reply sourcemap/mapper.go]: you think so? this is in errors - not spans... and only for frontend with sources in uploaded sourcemaps
i didn't want to bloat more the configuration space, but i can make it configurable if you prefer

File: sourcemap/mapper.go (hunk 2 above)
Comment (simitt) [reply sourcemap/mapper.go]: Oh ok. I agree that there is no need for logging when you check `if len(content) == 0 { return content }`, as this reflects something different than checking that `from` is not an overflow of the content array.

File: sourcemap/mapper.go (hunk 1 above)
Comment (simitt) [reply sourcemap/mapper.go]: Sourcemapping is generally enabled for frontend endpoints, so it will also be enabled for `transactions`, not only for `errors`. 
If we don't add the config option, it will be hard to give advice to customers in case they want to use sourcemapping but reduce storage.

**Comment by roncohen** [comment]
Awesome to have this in! We should probably add a changelog entry?
