### PR TITLE
Detect library_frames for frontend stacktraces.

### LINKED ISSUE #426: Detect if a stacktraceframe is library_frame or not.
Set boolean `library_frame` for every stacktrace frame if not set.

Allow for configurable regexp indicating a frame is a `library_frame`. 

@jahtalab will look into whether default values make sense if no config is given.

### PR DESCRIPTION
**Pull request by simitt**
closes #426 

@jahtalab fyi

### CODE REVIEW

File: model/stacktrace_frame.go [hunk 1]
```diff
@@ -43,6 +44,9 @@ func (s *StacktraceFrame) Transform(config *pr.Config, service Service) common.M
 	enhancer.Add(m, "module", s.Module)
 	enhancer.Add(m, "function", s.Function)
 	enhancer.Add(m, "vars", s.Vars)
+	if config != nil && config.LibraryPattern != nil && s.LibraryFrame == nil {
+		s.LibraryFrame = s.isLibraryFrame(config.LibraryPattern)
```
Comment (roncohen) [inline model/stacktrace_frame.go]: `isLibraryFrame` can never return `nil`, so it should return a `bool` instead of `*bool` and then we should store it in a variable here and set `s.LibraryFrame` to the address of that var.
