### PR TITLE
Fix numeric user id decoding

### LINKED ISSUE #2127: Metadata.User.id must be json encoded string
Howdy!

# Preamble
I ran into a either deserialisation or specification problem. The spec define the `id` field of the `Metadata.user` [schema](https://www.elastic.co/guide/en/apm/server/6.7/metadata-api.html#metadata-user-schema) that it can be of type `"type": ["string", "integer", "null"]`.

# Problem Description 
The `metadata.user.id` serialised as number represented json object (e.g. `"id": 123`) without the quotation marks as defined by the [JSON specification](https://tools.ietf.org/html/rfc7159#page-6) renders the apm-server to respond with  a `500: Internal Server Error`. But, when the `id` is serialized as a string (e.g. `"id": "123"`) the apm-server responds with `200`.

### Correct
```
"{"metadata": "service": {"name":"demo", "agent":{"name":"i-am-an-agent", "version":"6.7.0"}},"user":{"id":"12345","username":"foobar","email":"email@acme.com"}}}
```

### Failing
```
"{"metadata": "service": {"name":"demo", "agent":{"name":"i-am-an-agent", "version":"6.7.0"}},"user":{"id":12345,"username":"foobar","email":"email@acme.com"}}}
```

# APM Server Version
```
$ ./apm-server version
apm-server version 6.7.1 (amd64), libbeat 6.7.1 [5665711214eb3fcb956e7d1c61795e427bf97097 built 2019-04-02 14:55:06 +0000 UTC]
```

### PR DESCRIPTION
**Pull request by graphaelli**
already allowed by intake spec

backports part of #1783 

closes #2127

### CODE REVIEW

File: model/metadata/user.go [hunk 1]
```diff
@@ -42,12 +43,23 @@ func DecodeUser(input interface{}, err error) (*User, error) {
...
+
+	//id can be string or int
+	tmp := decoder.Interface(raw, "id")
+	if tmp != nil {
+		if t, ok := tmp.(json.Number); ok {
+			id := t.String()
+			user.Id = &id
+		} else if t, ok := tmp.(string); ok && t != "" {
+			user.Id = &t
+		}
```
Comment (graphaelli) [inline model/metadata/user.go]: @elastic/apm-server I've only backported what is on master for the moment but believe this should add a decoding error if `Id` is not a `json.Number` or `string`, even if that isn't possible via intake.

File: changelogs/6.7.asciidoc [hunk 2]
```diff
@@ -3,9 +3,22 @@
 
 https://github.com/elastic/apm-server/compare/6.6\...6.7[View commits]
 
+//* <<release-notes-6.721>>
```
Comment (simitt) [inline changelogs/6.7.asciidoc]: typo above
