### PR TITLE
consider exception or log message for grouping key

### LINKED ISSUE #402: Grouping key: Use `log.message` or `exception.message` if there's nothing else
There are edge cases in which agents will send up a `log.message` or `exception.message` but no stack trace or `param_message`. In these cases, APM Server should take `message` into account when calculating the grouping key.

### PR DESCRIPTION
**Pull request by graphaelli**
if nothing else is available

closes #402

### CODE REVIEW

File: processor/error/event.go [hunk 1]
```diff
@@ -123,40 +124,68 @@ func (e *Event) addGroupingKey() {
...
-		}
-		return s != nil
+func newGroupingKey() *groupingKey {
+	return &groupingKey{
+		hash:  md5.New(),
+		empty: true,
+	}
+}
+
+func (k *groupingKey) add(s *string) bool {
```
Comment (graphaelli) [inline processor/error/event.go]: these methods will panic if k is `nil` but since it's private and used in exactly one place I skipped guards.
