### PR TITLE
strip trailing slashes from kibana host configuration

### LINKED ISSUE #2647: Remove trailing slash for apm-server.kibana.host configuration option
If the value of `apm-server.kibana.host` config option contains a trailing slash, e.g. `http://kibana:5601/` the APM server fails to connect to Kibana. We can however check the presence of a trailing slash and remove it.

### PR DESCRIPTION
**Pull request by graphaelli**
closes #2647 

Can remove some duplication / risk of getting out of sync with beats framework if  elastic/beats#16042 is accepted

### CODE REVIEW

File: beater/config/config.go [hunk 1]
```diff
@@ -42,6 +44,45 @@ var (
 	regexObserverVersion = regexp.MustCompile("%.*{.*observer.version.?}")
 )
 
+type kibanaConfig struct {
+	Enabled bool                `config:"enabled"`
+	Config  kibana.ClientConfig `config:",inline"`
```
Comment (axw) [inline beater/config/config.go]: Can `kibana.ClientConfig` be embedded? It would be nice if we could turn (for example) `cfg.Kibana.Config.Host` into `cfg.Kibana.Host`.

File: beater/config/config.go [hunk 2]
```diff
@@ -42,6 +44,45 @@ var (
...
+}
+
+func (k *kibanaConfig) Unpack(c interface{}) error {
```
Comment (axw) [inline beater/config/config.go]: Would it make sense to make this `Unpack(cfg *ucfg.Config)` instead? i.e.

```go
func (k *kibanaConfig) Unpack(cfg *ucfg.Config) error {
    if err := cfg.Unpack(&k.Config); err != nil {
        return err
    }
    k.Enabled = cfg.Enabled()
    k.Config.Host = strings.TrimRight(k.Config.Host, "/")
    return nil
}
```

IIANM, that'll save a round-trip from Config -> interface{} -> Config

File: beater/config/config.go (hunk 1 above)
Comment (graphaelli) [reply beater/config/config.go]: Great idea.  I was trying to make `type kibanaConfig kibana.ClientConfig` originally and just embedding didn't even occur to me.

File: beater/config/config.go (hunk 2 above)
Comment (graphaelli) [reply beater/config/config.go]: @axw Another great suggestion, thanks.  I had to use `common.Config` to get the `Enabled()` method - would you double check 99decba9649b831ae79aec3464bdb8826eca8b01 to see if it looks right?

File: beater/api/mux.go [hunk 3]
```diff
@@ -179,15 +180,15 @@ type middlewareFunc func(*config.Config, *authorization.Handler, map[request.Res
 
 func agentConfigHandler(cfg *config.Config, authHandler *authorization.Handler, middlewareFunc middlewareFunc) (request.Handler, error) {
 	var client kibana.Client
-	if cfg.Kibana.Enabled() {
-		client = kibana.NewConnectingClient(cfg.Kibana)
+	if cfg.Kibana.Enabled {
+		client = kibana.NewConnectingClient(common.MustNewConfigFrom(cfg.Kibana))
```
Comment (axw) [inline beater/api/mux.go]: Can you please add a TODO (or just do it) to pass in the `kibana.ClientConfig` directly, rather than another round-trip through `libbeat/common`? Then we can change `apm-server/kibana` to call `libbeat/kibana.NewClientWithConfig`, rather than _yet another_ round-trip :)

**Comment by robgil** [comment]
# [Codecov](https://codecov.io/gh/elastic/apm-server/pull/3277?src=pr&el=h1) Report
> Merging [#3277](https://codecov.io/gh/elastic/apm-server/pull/3277?src=pr&el=desc) into [master](https://codecov.io/gh/elastic/apm-server/commit/0d828d7c5eaed62f5fb537a8217aafcb90ad3e98&el=desc) will **increase** coverage by `0.00%`.
> The diff coverage is `n/a`.



```diff
@@           Coverage Diff           @@
##           master    #3277   +/-   ##
=======================================
  Coverage   79.33%   79.34%           
=======================================
  Files         107      107           
  Lines        5600     5621   +21     
=======================================
+ Hits         4443     4460   +17     
- Misses       1157     1161    +4     
```

File: beater/config/config.go [hunk 4]
```diff
@@ -42,6 +44,40 @@ var (
...
 
+type kibanaConfig struct {
+	Enabled             bool `config:"enabled"`
+	kibana.ClientConfig `config:",inline"`
+}
+
+func (k *kibanaConfig) Unpack(cfg *common.Config) error {
+	if cfg == nil {
+		return nil
+	}
```
Comment (axw) [inline beater/config/config.go]: Pretty sure this is unnecessary. go-ucfg's `Config.Unpack` will return an error if the config is nil, before calling into the provided value.

File: beater/config/config.go [hunk 5]
```diff
@@ -42,6 +44,40 @@ var (
 	regexObserverVersion = regexp.MustCompile("%.*{.*observer.version.?}")
 )
 
+type kibanaConfig struct {
```
[the remark this answers is not in the document]
Comment (graphaelli) [reply beater/config/config.go]: done

File: beater/config/config.go (hunk 4 above)
Comment (graphaelli) [reply beater/config/config.go]: I noticed you removed it in the last suggestion but hesitated since this is exported.  On second thought, taking the suggestion.

File: beater/api/mux.go (hunk 3 above)
Comment (graphaelli) [reply beater/api/mux.go]: Good call, just did it

**Comment by graphaelli** [comment]
holding off on merging this for a day or two to see if we can get the upstream changes into beats first
