### PR TITLE
Fix legacy tracer initialization

### LINKED ISSUE #3950: Legacy tracer config not recognized when passed as command line arg
While `apm-server.instrumentation.enabled: true` works as expected if set in `apm-server.yml`, the same is not true when passed as argument with `-E`.

This is because command line config settings are merged after the overrides hook is called from libbeat, which is what we are using to copy `apm-server.instrumentation` to `instrumentation`.

Caused by #3836

### PR DESCRIPTION
**Pull request by jalvz**
## Motivation/summary

Change the approach to init `apm-server.instrumentation`: handle it in `beater.go` instead of relying on the config overrides logic

**Update**: additionally, enable the profile endpoint always, without checking the configuration. this wasn't working neither when using the new configuration from libbeat.  

## Checklist

- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

I have considered changes for:
- [ ] documentation
- [ ] logging (add log lines, choose appropriate log selector, etc.)
- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))
- [x] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)
- [ ] telemetry
- [ ] Elasticsearch Service (https://cloud.elastic.co)
- [ ] Elastic Cloud Enterprise (https://www.elastic.co/products/ece)
- [ ] Elastic Cloud on Kubernetes (https://www.elastic.co/elastic-cloud-kubernetes)

## How to test these changes

- Check that both `apm-server.instrumentation.*` and `instrumentation.*` settings work when reading config from a file or passing it with `-E` command args.

- Check that `instrumentation.profile.*` settings work as well.

- Check that `hosts` config works when explicitly set.

## Related issues

Fixes #3950

### CODE REVIEW

**Comment by jalvz** [comment]
jenkins run hey-apm tests please

File: beater/api/mux.go [hunk 1]
```diff
@@ -91,15 +91,7 @@ func NewMux(beaterConfig *config.Config, report publish.Reporter) (*http.ServeMu
...
-	}
-
-	// Profiling is currently experimental, and intended for profiling the
-	// server itself, so we only add the route if self-profiling is enabled.
-	if beaterConfig.SelfInstrumentation.IsEnabled() {
-		if beaterConfig.SelfInstrumentation.Profiling.CPU.IsEnabled() ||
-			beaterConfig.SelfInstrumentation.Profiling.Heap.IsEnabled() {
-			routeMap = append(routeMap, route{ProfilePath, profileHandler})
-		}
+		{ProfilePath, profileHandler},
```
Comment (simitt) [inline beater/api/mux.go:94]: nit: could you still keep a comment that the profiling is currently beta

File: beater/beater.go [hunk 2]
```diff
@@ -217,6 +218,51 @@ func (bt *beater) registerPipelineCallback(b *beat.Beat) error {
...
+}
+
+// initLegacyTracer exists for backwards compatibility and it should be removed in 8.0
+// it does not instrument the beat output
+func initLegacyTracer(info beat.Info, cfg *config.Config) (*apm.Tracer, net.Listener, error) {
+	selfInstrumentation := cfg.SelfInstrumentation
+	if selfInstrumentation == nil || !selfInstrumentation.IsEnabled() {
+		return apm.DefaultTracer, nil, nil
+	}
+	conf := common.MustNewConfigFrom(cfg.SelfInstrumentation)
```
Comment (simitt) [inline beater/beater.go:244]: `MustNewConfigFrom` panics in case an error occurs. So far we use it in tests or when the whole input config has fixed values. I don't think we shoul be using it with user provided input and suggest to instead use `NewConfigFrom`  with the additional error check.

File: tests/system/test_instrumentation.py [hunk 3]
```diff
@@ -15,6 +15,8 @@
 os.environ["ELASTIC_APM_API_REQUEST_TIME"] = "1s"
 
 
+# Exercises the DEPRECATED apm-server.instrumentation.* config
+
```
Comment (simitt) [inline tests/system/test_instrumentation.py:19]: The tests in `test_libbeat_instrumentation` are copies of this file. I assume you didn't DRY the tests based on the fact that the support for `apm-server.instrumentation`  will be removed in 8.0.?
Please add a comment in both, to make future changes to the test cases in both files, and to delete this file for 8.0.
