### PR TITLE
Fix panic when a signal is delivered before the server is instantiated

### LINKED ISSUE #514: panic on signal during startup
Still investigating if the kibana dashboard setup is related or just a convenient way to reproduce this.  Reliably getting a panic on ctrl-c immediately after start up using:

```
$ ./apm-server -e -E setup.kibana.host=localhost:5601 -E setup.dashboards.enabled=true
...
2018-01-17T16:51:38.291-0500	INFO	[monitoring]	log/log.go:95	Starting metrics logging every 30s
2018-01-17T16:51:38.292-0500	INFO	elasticsearch/client.go:145	Elasticsearch url: http://localhost:9200
2018-01-17T16:51:38.298-0500	INFO	elasticsearch/client.go:689	Connected to Elasticsearch version 6.2.0
2018-01-17T16:51:38.298-0500	INFO	kibana/client.go:69	Kibana url: http://localhost:5601
^C
2018-01-17T16:51:38.736-0500	INFO	beater/beater.go:72	stopping apm-server...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6c pc=0x42aad44]
goroutine 25 [running]:
net/http.(*Server).Shutdown(0x0, 0x52a4280, 0xc4202ba180, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2488 +0x54
github.com/elastic/apm-server/beater.stop(0x0, 0x12a05f200)
	/go/src/github.com/elastic/apm-server/beater/server.go:51 +0x9b
github.com/elastic/apm-server/beater.(*beater).Stop(0xc42014e500)
	/go/src/github.com/elastic/apm-server/beater/beater.go:73 +0x6f
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/beat.(Beater).Stop-fm()
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go:288 +0x2f
sync.(*Once).Do(0xc420158250, 0xc4201d2140)
	/usr/local/Cellar/go/1.9.2/libexec/src/sync/once.go:44 +0xbe
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/service.HandleSignals.func1(0xc420394300, 0xc420158250, 0xc4201d2140)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/service/service.go:34 +0x99
created by github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/service.HandleSignals
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/service/service.go:31 +0x106
```

### PR DESCRIPTION
**Pull request by jalvz**
Introduce a flag and a mutex in the beater so that we can't stop the server before assigning it (ie. read before write)

fixes #514

### CODE REVIEW

File: beater/beater.go [hunk 1]
```diff
@@ -7,14 +7,18 @@ import (
 	"net/http"
 	"regexp"
 
+	"sync"
```
[the remark this answers is not in the document]
Comment (jalvz) [reply beater/beater.go]: I always have this problem, this is how it looks after running `gofmt` and `goimports`. Eventually got tired of fixing white lines in import blocks manually... it might be because of my IDE, but `make check` seems to be happy with this indeed.

**Comment by jalvz** [comment]
thanks Gil, comments addressed here 0731cbe4983caeb907641779709386e3fc165892

File: beater/beater.go [hunk 2]
```diff
@@ -6,15 +6,18 @@ import (
...
 	"github.com/elastic/beats/libbeat/beat"
 	"github.com/elastic/beats/libbeat/common"
 	"github.com/elastic/beats/libbeat/logp"
 )
 
 type beater struct {
-	config *Config
-	server *http.Server
+	config  *Config
+	mutex   sync.RWMutex // guards server and stopped
```
Comment (marclop) [inline beater/beater.go]: no need for a RWMutex if `RLock` and `RUnlock` isn't used.

Comment (jalvz) [reply beater/beater.go]: true, good point
